name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      uses: actions/run-command@v1
      with:
        command: dotnet build MyProject.csproj

    - name: Checkout actions repository
      uses: actions/checkout@v2
      with:
        repository: actions/checkout

    - name: Run custom action
      uses: ./path/to/custom/action
      with:
        command: echo "Hello, world!"
